[package]
name = "my_fft"
version = "0.1.0"
authors = ["hatoo <hato2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2"
rayon = "1"

[dev-dependencies]
rustfft = "3"
rand = "0.7"
